name: Deploy Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy-infra:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform init

      - name: Import Cloud Run service
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform import google_cloud_run_service.metrics_api locations/us-central1/namespaces/${{ secrets.GCP_PROJECT_ID }}/services/metrics-api || echo "Already imported"

      - name: Import Pub/Sub topic
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform import google_pubsub_topic.metrics projects/${{ secrets.GCP_PROJECT_ID }}/topics/metrics-topic || echo "Already imported"

      - name: Import BigQuery dataset
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform import google_bigquery_dataset.metrics projects/${{ secrets.GCP_PROJECT_ID }}/datasets/metrics_dataset || echo "Already imported"

      - name: Import BigQuery table
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          terraform import google_bigquery_table.raw_metrics projects/${{ secrets.GCP_PROJECT_ID }}/datasets/metrics_dataset/tables/raw_metrics || echo "Already imported"

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform apply -auto-approve

  deploy-cloud-run:
    name: Deploy Cloud Run Service
    needs: deploy-infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          cd metrics-ingestion
          gcloud run deploy metrics-api \
            --source=. \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
