name: Deploy Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy-infra:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform  # All terraform commands run in ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # You can update this as needed

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform init

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform apply -auto-approve

  deploy-cloud-run:
    name: Deploy Cloud Run Service
    needs: deploy-infra   # Wait for Terraform to finish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          cd metrics-ingestion
          gcloud run deploy metrics-api \
            --source=. \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
